# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointment_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 468)
        Dialog.setStyleSheet("background-color: rgba(170, 170, 255,.4);")
        self.vname = QtWidgets.QLabel(Dialog)
        self.vname.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.vname.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.vname.setObjectName("vname")
        self.phone = QtWidgets.QLabel(Dialog)
        self.phone.setGeometry(QtCore.QRect(30, 70, 111, 31))
        self.phone.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.phone.setObjectName("phone")
        self.appointment_table = QtWidgets.QTableWidget(Dialog)
        self.appointment_table.setGeometry(QtCore.QRect(30, 250, 731, 150))
        self.appointment_table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"MS Shell Dlg 2\";")
        self.appointment_table.setObjectName("appointment_table")
        self.appointment_table.setColumnCount(6)
        self.appointment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(5, item)
        self.visit_date_2 = QtWidgets.QLabel(Dialog)
        self.visit_date_2.setGeometry(QtCore.QRect(30, 220, 731, 31))
        self.visit_date_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.visit_date_2.setObjectName("visit_date_2")
        self.search_name_edit = QtWidgets.QTextEdit(Dialog)
        self.search_name_edit.setGeometry(QtCore.QRect(1030, 30, 141, 31))
        self.search_name_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search_name_edit.setObjectName("search_name_edit")
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(1030, 110, 101, 31))
        self.search_btn.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.search_btn.setObjectName("search_btn")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(1035, 120, 100, 30))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.visit_date_3 = QtWidgets.QLabel(Dialog)
        self.visit_date_3.setGeometry(QtCore.QRect(930, 30, 101, 31))
        self.visit_date_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.visit_date_3.setObjectName("visit_date_3")
        self.visit_date_4 = QtWidgets.QLabel(Dialog)
        self.visit_date_4.setGeometry(QtCore.QRect(930, 70, 101, 31))
        self.visit_date_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.visit_date_4.setObjectName("visit_date_4")
        self.search_phone_edit = QtWidgets.QTextEdit(Dialog)
        self.search_phone_edit.setGeometry(QtCore.QRect(1030, 70, 141, 31))
        self.search_phone_edit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.search_phone_edit.setObjectName("search_phone_edit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(880, 210, 151, 30))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.cancel_appointment = QtWidgets.QPushButton(Dialog)
        self.cancel_appointment.setGeometry(QtCore.QRect(879, 200, 151, 30))
        self.cancel_appointment.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/patientdownload .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_appointment.setIcon(icon)
        self.cancel_appointment.setObjectName("cancel_appointment")
        self.calendar = QtWidgets.QCalendarWidget(Dialog)
        self.calendar.setGeometry(QtCore.QRect(450, 10, 312, 183))
        self.calendar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.calendar.setObjectName("calendar")
        self.return_btn = QtWidgets.QPushButton(Dialog)
        self.return_btn.setGeometry(QtCore.QRect(30, 410, 140, 30))
        self.return_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.return_btn.setIcon(icon)
        self.return_btn.setObjectName("return_btn")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 420, 140, 30))
        self.label_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.Updat_btn = QtWidgets.QPushButton(Dialog)
        self.Updat_btn.setGeometry(QtCore.QRect(620, 410, 140, 30))
        self.Updat_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.Updat_btn.setIcon(icon)
        self.Updat_btn.setObjectName("Updat_btn")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(620, 420, 140, 30))
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(640, 280, 101, 22))
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.v_name = QtWidgets.QLabel(Dialog)
        self.v_name.setGeometry(QtCore.QRect(140, 30, 110, 30))
        self.v_name.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.v_name.setObjectName("v_name")
        self.v_phone = QtWidgets.QLabel(Dialog)
        self.v_phone.setGeometry(QtCore.QRect(140, 70, 110, 30))
        self.v_phone.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.v_phone.setObjectName("v_phone")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(30, 120, 221, 41))
        self.timeEdit.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgba(255, 255, 255,.5);")
        self.timeEdit.setObjectName("timeEdit")
        self.label_7.raise_()
        self.vname.raise_()
        self.phone.raise_()
        self.appointment_table.raise_()
        self.visit_date_2.raise_()
        self.search_name_edit.raise_()
        self.label_5.raise_()
        self.search_btn.raise_()
        self.visit_date_3.raise_()
        self.visit_date_4.raise_()
        self.search_phone_edit.raise_()
        self.label_6.raise_()
        self.cancel_appointment.raise_()
        self.calendar.raise_()
        self.label_4.raise_()
        self.return_btn.raise_()
        self.Updat_btn.raise_()
        self.comboBox.raise_()
        self.v_name.raise_()
        self.v_phone.raise_()
        self.timeEdit.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.vname.setText(_translate("Dialog", "Visitor Name"))
        self.phone.setText(_translate("Dialog", "Phone"))
        item = self.appointment_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Date Registered"))
        item = self.appointment_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "First Name"))
        item = self.appointment_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Phone"))
        item = self.appointment_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Visit Date"))
        item = self.appointment_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Visit time"))
        item = self.appointment_table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Dentist Name"))
        self.visit_date_2.setText(_translate("Dialog", "Appointment Table"))
        self.search_btn.setText(_translate("Dialog", "Search "))
        self.visit_date_3.setText(_translate("Dialog", "Fisrt Name"))
        self.visit_date_4.setText(_translate("Dialog", "Phone"))
        self.cancel_appointment.setText(_translate("Dialog", "Cancel Appointment"))
        self.return_btn.setText(_translate("Dialog", "Return"))
        self.Updat_btn.setText(_translate("Dialog", "Update"))
        self.comboBox.setItemText(0, _translate("Dialog", "Active"))
        self.comboBox.setItemText(1, _translate("Dialog", "Cancelled"))
        self.comboBox.setItemText(2, _translate("Dialog", "Completed"))
        self.v_name.setText(_translate("Dialog", "v_name"))
        self.v_phone.setText(_translate("Dialog", "v_phone"))
