# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appointment_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 680)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.side_bar = QtWidgets.QWidget(Dialog)
        self.side_bar.setGeometry(QtCore.QRect(0, 0, 160, 681))
        self.side_bar.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.5);\n"
"\n"
"")
        self.side_bar.setObjectName("side_bar")
        self.patient_btn = QtWidgets.QPushButton(self.side_bar)
        self.patient_btn.setGeometry(QtCore.QRect(10, 180, 140, 40))
        self.patient_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/patientdownload .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient_btn.setIcon(icon)
        self.patient_btn.setObjectName("patient_btn")
        self.dash_btn = QtWidgets.QPushButton(self.side_bar)
        self.dash_btn.setGeometry(QtCore.QRect(10, 80, 140, 40))
        self.dash_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Medico_modern/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dash_btn.setIcon(icon1)
        self.dash_btn.setObjectName("dash_btn")
        self.appointment_btn = QtWidgets.QPushButton(self.side_bar)
        self.appointment_btn.setGeometry(QtCore.QRect(10, 480, 140, 40))
        self.appointment_btn.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Medico_modern/appointmentdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointment_btn.setIcon(icon2)
        self.appointment_btn.setObjectName("appointment_btn")
        self.dentist_btn = QtWidgets.QPushButton(self.side_bar)
        self.dentist_btn.setGeometry(QtCore.QRect(10, 580, 140, 40))
        self.dentist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Medico_modern/dentistimages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dentist_btn.setIcon(icon3)
        self.dentist_btn.setObjectName("dentist_btn")
        self.payment_btn = QtWidgets.QPushButton(self.side_bar)
        self.payment_btn.setGeometry(QtCore.QRect(10, 280, 140, 40))
        self.payment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Medico_modern/billingdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_btn.setIcon(icon4)
        self.payment_btn.setObjectName("payment_btn")
        self.expense_btn = QtWidgets.QPushButton(self.side_bar)
        self.expense_btn.setGeometry(QtCore.QRect(10, 380, 140, 40))
        self.expense_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.expense_btn.setIcon(icon4)
        self.expense_btn.setObjectName("expense_btn")
        self.label_4 = QtWidgets.QLabel(self.side_bar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.vname = QtWidgets.QLabel(Dialog)
        self.vname.setGeometry(QtCore.QRect(200, 30, 121, 31))
        self.vname.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.vname.setObjectName("vname")
        self.vname_edit = QtWidgets.QTextEdit(Dialog)
        self.vname_edit.setGeometry(QtCore.QRect(320, 30, 141, 31))
        self.vname_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.vname_edit.setObjectName("vname_edit")
        self.phone = QtWidgets.QLabel(Dialog)
        self.phone.setGeometry(QtCore.QRect(200, 70, 121, 31))
        self.phone.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.phone.setObjectName("phone")
        self.phone_edit = QtWidgets.QTextEdit(Dialog)
        self.phone_edit.setGeometry(QtCore.QRect(320, 70, 141, 31))
        self.phone_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.phone_edit.setObjectName("phone_edit")
        self.visit_time = QtWidgets.QLabel(Dialog)
        self.visit_time.setGeometry(QtCore.QRect(530, 70, 101, 31))
        self.visit_time.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_time.setObjectName("visit_time")
        self.visit_date = QtWidgets.QLabel(Dialog)
        self.visit_date.setGeometry(QtCore.QRect(530, 110, 311, 31))
        self.visit_date.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_date.setObjectName("visit_date")
        self.appointment_table = QtWidgets.QTableWidget(Dialog)
        self.appointment_table.setGeometry(QtCore.QRect(200, 350, 671, 311))
        self.appointment_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.appointment_table.setStyleSheet("background-color: rgba(255, 255, 255,.85);\n"
"font:  12pt \"Segoe UI \";")
        self.appointment_table.setObjectName("appointment_table")
        self.appointment_table.setColumnCount(8)
        self.appointment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(7, item)
        self.visit_date_2 = QtWidgets.QLabel(Dialog)
        self.visit_date_2.setGeometry(QtCore.QRect(200, 320, 671, 31))
        self.visit_date_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_date_2.setObjectName("visit_date_2")
        self.search_name_edit = QtWidgets.QTextEdit(Dialog)
        self.search_name_edit.setGeometry(QtCore.QRect(1010, 70, 141, 31))
        self.search_name_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.search_name_edit.setObjectName("search_name_edit")
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(1165, 220, 101, 31))
        self.search_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1281, 680))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/atikah-akhtar-XJptUS8nbhs-unsplash.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.add_appointment_btn = QtWidgets.QPushButton(Dialog)
        self.add_appointment_btn.setGeometry(QtCore.QRect(210, 200, 200, 30))
        self.add_appointment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.add_appointment_btn.setIcon(icon)
        self.add_appointment_btn.setObjectName("add_appointment_btn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(215, 205, 200, 30))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(1170, 230, 100, 30))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.visit_date_3 = QtWidgets.QLabel(Dialog)
        self.visit_date_3.setGeometry(QtCore.QRect(910, 70, 101, 31))
        self.visit_date_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_date_3.setObjectName("visit_date_3")
        self.visit_date_4 = QtWidgets.QLabel(Dialog)
        self.visit_date_4.setGeometry(QtCore.QRect(910, 110, 101, 31))
        self.visit_date_4.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_date_4.setObjectName("visit_date_4")
        self.search_phone_edit = QtWidgets.QTextEdit(Dialog)
        self.search_phone_edit.setGeometry(QtCore.QRect(1010, 110, 141, 31))
        self.search_phone_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.search_phone_edit.setObjectName("search_phone_edit")
        self.dname = QtWidgets.QLabel(Dialog)
        self.dname.setGeometry(QtCore.QRect(200, 110, 121, 31))
        self.dname.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.dname.setObjectName("dname")
        self.dname_edit = QtWidgets.QTextEdit(Dialog)
        self.dname_edit.setGeometry(QtCore.QRect(320, 110, 141, 31))
        self.dname_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.dname_edit.setObjectName("dname_edit")
        self.timeEdit = QtWidgets.QTimeEdit(Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(630, 70, 131, 31))
        self.timeEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.timeEdit.setStyleSheet("font: 12pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 255);")
        self.timeEdit.setObjectName("timeEdit")
        self.visit_date_5 = QtWidgets.QLabel(Dialog)
        self.visit_date_5.setGeometry(QtCore.QRect(630, 140, 131, 20))
        self.visit_date_5.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  8pt \"Segoe UI \";")
        self.visit_date_5.setObjectName("visit_date_5")
        self.pat_id_edit = QtWidgets.QTextEdit(Dialog)
        self.pat_id_edit.setGeometry(QtCore.QRect(750, 30, 141, 31))
        self.pat_id_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.pat_id_edit.setObjectName("pat_id_edit")
        self.vname_2 = QtWidgets.QLabel(Dialog)
        self.vname_2.setGeometry(QtCore.QRect(530, 30, 221, 31))
        self.vname_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.vname_2.setObjectName("vname_2")
        self.vname_3 = QtWidgets.QLabel(Dialog)
        self.vname_3.setGeometry(QtCore.QRect(910, 180, 221, 31))
        self.vname_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.vname_3.setObjectName("vname_3")
        self.search_pat_id_edit = QtWidgets.QTextEdit(Dialog)
        self.search_pat_id_edit.setGeometry(QtCore.QRect(1130, 180, 141, 31))
        self.search_pat_id_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.search_pat_id_edit.setObjectName("search_pat_id_edit")
        self.visit_date_6 = QtWidgets.QLabel(Dialog)
        self.visit_date_6.setGeometry(QtCore.QRect(910, 150, 21, 20))
        self.visit_date_6.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  8pt \"Segoe UI \";")
        self.visit_date_6.setObjectName("visit_date_6")
        self.vname_4 = QtWidgets.QLabel(Dialog)
        self.vname_4.setGeometry(QtCore.QRect(910, 30, 361, 31))
        self.vname_4.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.vname_4.setObjectName("vname_4")
        self.calendar = QtWidgets.QCalendarWidget(Dialog)
        self.calendar.setGeometry(QtCore.QRect(530, 140, 311, 171))
        self.calendar.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.calendar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"alternate-background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.calendar.setGridVisible(False)
        self.calendar.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendar.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.SingleLetterDayNames)
        self.calendar.setNavigationBarVisible(True)
        self.calendar.setDateEditEnabled(True)
        self.calendar.setObjectName("calendar")
        self.calender_date = QtWidgets.QCalendarWidget(Dialog)
        self.calender_date.setGeometry(QtCore.QRect(910, 350, 321, 171))
        self.calender_date.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.calender_date.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgba(0, 0, 0,.85);\n"
"")
        self.calender_date.setGridVisible(False)
        self.calender_date.setObjectName("calender_date")
        self.visit_date_7 = QtWidgets.QLabel(Dialog)
        self.visit_date_7.setGeometry(QtCore.QRect(910, 320, 321, 31))
        self.visit_date_7.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.visit_date_7.setObjectName("visit_date_7")
        self.label.raise_()
        self.side_bar.raise_()
        self.vname.raise_()
        self.vname_edit.raise_()
        self.phone.raise_()
        self.phone_edit.raise_()
        self.visit_time.raise_()
        self.appointment_table.raise_()
        self.visit_date_2.raise_()
        self.search_name_edit.raise_()
        self.label_3.raise_()
        self.add_appointment_btn.raise_()
        self.label_5.raise_()
        self.search_btn.raise_()
        self.visit_date_3.raise_()
        self.visit_date_4.raise_()
        self.search_phone_edit.raise_()
        self.dname.raise_()
        self.dname_edit.raise_()
        self.timeEdit.raise_()
        self.visit_date_5.raise_()
        self.pat_id_edit.raise_()
        self.vname_2.raise_()
        self.vname_3.raise_()
        self.search_pat_id_edit.raise_()
        self.visit_date_6.raise_()
        self.vname_4.raise_()
        self.calendar.raise_()
        self.visit_date.raise_()
        self.calender_date.raise_()
        self.visit_date_7.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.appointment_btn, self.dentist_btn)
        Dialog.setTabOrder(self.dentist_btn, self.vname_edit)
        Dialog.setTabOrder(self.vname_edit, self.phone_edit)
        Dialog.setTabOrder(self.phone_edit, self.dname_edit)
        Dialog.setTabOrder(self.dname_edit, self.pat_id_edit)
        Dialog.setTabOrder(self.pat_id_edit, self.timeEdit)
        Dialog.setTabOrder(self.timeEdit, self.add_appointment_btn)
        Dialog.setTabOrder(self.add_appointment_btn, self.search_name_edit)
        Dialog.setTabOrder(self.search_name_edit, self.search_phone_edit)
        Dialog.setTabOrder(self.search_phone_edit, self.search_pat_id_edit)
        Dialog.setTabOrder(self.search_pat_id_edit, self.search_btn)
        Dialog.setTabOrder(self.search_btn, self.dash_btn)
        Dialog.setTabOrder(self.dash_btn, self.patient_btn)
        Dialog.setTabOrder(self.patient_btn, self.payment_btn)
        Dialog.setTabOrder(self.payment_btn, self.expense_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.patient_btn.setText(_translate("Dialog", "Patients"))
        self.dash_btn.setText(_translate("Dialog", "Dashboard"))
        self.appointment_btn.setText(_translate("Dialog", "Appointments"))
        self.dentist_btn.setText(_translate("Dialog", "Dentists"))
        self.payment_btn.setText(_translate("Dialog", "Payments"))
        self.expense_btn.setText(_translate("Dialog", "Expense"))
        self.label_4.setText(_translate("Dialog", " Medico App "))
        self.vname.setText(_translate("Dialog", "Visitor Name"))
        self.phone.setText(_translate("Dialog", "Phone"))
        self.visit_time.setText(_translate("Dialog", "Visit Time"))
        self.visit_date.setText(_translate("Dialog", "Visit Date"))
        item = self.appointment_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Date Registered"))
        item = self.appointment_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Patient ID"))
        item = self.appointment_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "First Name"))
        item = self.appointment_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Phone"))
        item = self.appointment_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Visit Date(dd-MM-yyyy)"))
        item = self.appointment_table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Visit time"))
        item = self.appointment_table.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Dentist Name"))
        item = self.appointment_table.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Status"))
        self.visit_date_2.setText(_translate("Dialog", "Appointment Table"))
        self.search_btn.setText(_translate("Dialog", "Search "))
        self.add_appointment_btn.setText(_translate("Dialog", "Add Appointment"))
        self.visit_date_3.setText(_translate("Dialog", "First Name"))
        self.visit_date_4.setText(_translate("Dialog", "Phone"))
        self.dname.setText(_translate("Dialog", "Dentist Name"))
        self.visit_date_5.setText(_translate("Dialog", "mm/dd/yyyy"))
        self.vname_2.setText(_translate("Dialog", "Patient ID (If registered)"))
        self.vname_3.setText(_translate("Dialog", "Patient ID (If registered)"))
        self.visit_date_6.setText(_translate("Dialog", "OR"))
        self.vname_4.setText(_translate("Dialog", "Search for individual appointments"))
        self.visit_date_7.setText(_translate("Dialog", "Search Appointment by date"))
