# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(538, 239)
        Dialog.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.cnf_yes_btn = QtWidgets.QPushButton(Dialog)
        self.cnf_yes_btn.setGeometry(QtCore.QRect(80, 150, 101, 41))
        self.cnf_yes_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 0, 0);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(255,0, 0, 200);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    background-color: rgba(255,0, 0, 200);\n"
"}")
        self.cnf_yes_btn.setObjectName("cnf_yes_btn")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(90, 160, 100, 40))
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.warning_label = QtWidgets.QLabel(Dialog)
        self.warning_label.setGeometry(QtCore.QRect(40, 30, 481, 71))
        self.warning_label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.warning_label.setObjectName("warning_label")
        self.cnf_no_btn = QtWidgets.QPushButton(Dialog)
        self.cnf_no_btn.setGeometry(QtCore.QRect(320, 150, 101, 41))
        self.cnf_no_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border-top-left-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.cnf_no_btn.setObjectName("cnf_no_btn")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(330, 160, 100, 40))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_7.raise_()
        self.cnf_yes_btn.raise_()
        self.warning_label.raise_()
        self.label_8.raise_()
        self.cnf_no_btn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cnf_yes_btn.setText(_translate("Dialog", "Yes"))
        self.warning_label.setText(_translate("Dialog", "Are you sure you want to delete this patient and their information?"))
        self.cnf_no_btn.setText(_translate("Dialog", "Return"))
