# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files_updt.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 400)
        Dialog.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.6);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(170, 170, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0.403, y1:0.3125, x2:1, y2:1, stop:0 rgba(170, 170, 255, 255), stop:1 rgba(169, 255, 185, 255));")
        self.fname_srch = QtWidgets.QLabel(Dialog)
        self.fname_srch.setGeometry(QtCore.QRect(25, 20, 700, 41))
        self.fname_srch.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"font: 75 bold 14pt \"Segoe UI\";")
        self.fname_srch.setAlignment(QtCore.Qt.AlignCenter)
        self.fname_srch.setObjectName("fname_srch")
        self.est_cost = QtWidgets.QLabel(Dialog)
        self.est_cost.setGeometry(QtCore.QRect(35, 81, 161, 31))
        self.est_cost.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.est_cost.setObjectName("est_cost")
        self.estd_cost_edit = QtWidgets.QTextEdit(Dialog)
        self.estd_cost_edit.setGeometry(QtCore.QRect(195, 81, 141, 31))
        self.estd_cost_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.estd_cost_edit.setObjectName("estd_cost_edit")
        self.discount = QtWidgets.QLabel(Dialog)
        self.discount.setGeometry(QtCore.QRect(35, 132, 161, 31))
        self.discount.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.discount.setObjectName("discount")
        self.discount_edit = QtWidgets.QTextEdit(Dialog)
        self.discount_edit.setGeometry(QtCore.QRect(195, 132, 141, 31))
        self.discount_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.discount_edit.setObjectName("discount_edit")
        self.updt_file_btn = QtWidgets.QPushButton(Dialog)
        self.updt_file_btn.setGeometry(QtCore.QRect(35, 305, 150, 30))
        self.updt_file_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_file_btn.setObjectName("updt_file_btn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 310, 150, 30))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 360, 150, 30))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(35, 355, 150, 30))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.desc_edit = QtWidgets.QTextEdit(Dialog)
        self.desc_edit.setGeometry(QtCore.QRect(350, 110, 381, 251))
        self.desc_edit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.desc_edit.setObjectName("desc_edit")
        self.est_cost_2 = QtWidgets.QLabel(Dialog)
        self.est_cost_2.setGeometry(QtCore.QRect(350, 80, 381, 31))
        self.est_cost_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.est_cost_2.setObjectName("est_cost_2")
        self.fname_srch.raise_()
        self.est_cost.raise_()
        self.estd_cost_edit.raise_()
        self.discount.raise_()
        self.discount_edit.raise_()
        self.label_3.raise_()
        self.updt_file_btn.raise_()
        self.label_6.raise_()
        self.cancel_btn.raise_()
        self.desc_edit.raise_()
        self.est_cost_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.estd_cost_edit, self.discount_edit)
        Dialog.setTabOrder(self.discount_edit, self.desc_edit)
        Dialog.setTabOrder(self.desc_edit, self.updt_file_btn)
        Dialog.setTabOrder(self.updt_file_btn, self.cancel_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fname_srch.setText(_translate("Dialog", "Fill only the field you want to update."))
        self.est_cost.setText(_translate("Dialog", "Estimated Cost:"))
        self.discount.setText(_translate("Dialog", "Discount:"))
        self.updt_file_btn.setText(_translate("Dialog", "Update File"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
        self.est_cost_2.setText(_translate("Dialog", "Desciption:"))
