# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'files_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(740, 636)
        Dialog.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.6);\n"
"background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0.333333 rgba(170, 170, 255, 255), stop:0.988701 rgba(128, 255, 164, 255));")
        self.fname_srch = QtWidgets.QLabel(Dialog)
        self.fname_srch.setGeometry(QtCore.QRect(25, 20, 101, 31))
        self.fname_srch.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.fname_srch.setObjectName("fname_srch")
        self.fname_srch_edit = QtWidgets.QTextEdit(Dialog)
        self.fname_srch_edit.setGeometry(QtCore.QRect(125, 20, 601, 31))
        self.fname_srch_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.fname_srch_edit.setObjectName("fname_srch_edit")
        self.file_desc_edit = QtWidgets.QTextEdit(Dialog)
        self.file_desc_edit.setGeometry(QtCore.QRect(25, 100, 700, 291))
        self.file_desc_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.file_desc_edit.setObjectName("file_desc_edit")
        self.add_complain = QtWidgets.QLabel(Dialog)
        self.add_complain.setGeometry(QtCore.QRect(25, 70, 700, 31))
        self.add_complain.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.add_complain.setObjectName("add_complain")
        self.est_cost = QtWidgets.QLabel(Dialog)
        self.est_cost.setGeometry(QtCore.QRect(35, 440, 161, 31))
        self.est_cost.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.est_cost.setObjectName("est_cost")
        self.estd_cost_edit = QtWidgets.QTextEdit(Dialog)
        self.estd_cost_edit.setGeometry(QtCore.QRect(195, 440, 141, 31))
        self.estd_cost_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.estd_cost_edit.setObjectName("estd_cost_edit")
        self.discount = QtWidgets.QLabel(Dialog)
        self.discount.setGeometry(QtCore.QRect(35, 480, 161, 31))
        self.discount.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.discount.setObjectName("discount")
        self.discount_edit = QtWidgets.QTextEdit(Dialog)
        self.discount_edit.setGeometry(QtCore.QRect(195, 480, 141, 31))
        self.discount_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.discount_edit.setObjectName("discount_edit")
        self.add_file_btn = QtWidgets.QPushButton(Dialog)
        self.add_file_btn.setGeometry(QtCore.QRect(525, 430, 150, 30))
        self.add_file_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.add_file_btn.setObjectName("add_file_btn")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(530, 435, 150, 30))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(530, 500, 150, 30))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.cancel_btn = QtWidgets.QPushButton(Dialog)
        self.cancel_btn.setGeometry(QtCore.QRect(525, 495, 150, 30))
        self.cancel_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.cancel_btn.setObjectName("cancel_btn")
        self.fname_srch.raise_()
        self.fname_srch_edit.raise_()
        self.file_desc_edit.raise_()
        self.add_complain.raise_()
        self.est_cost.raise_()
        self.estd_cost_edit.raise_()
        self.discount.raise_()
        self.discount_edit.raise_()
        self.label_3.raise_()
        self.add_file_btn.raise_()
        self.label_6.raise_()
        self.cancel_btn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.fname_srch.setText(_translate("Dialog", "File Name:"))
        self.add_complain.setText(_translate("Dialog", "File Description"))
        self.est_cost.setText(_translate("Dialog", "Estimated Cost:"))
        self.discount.setText(_translate("Dialog", "Discount:"))
        self.add_file_btn.setText(_translate("Dialog", "Add File"))
        self.cancel_btn.setText(_translate("Dialog", "Cancel"))
