# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 680)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.side_bar = QtWidgets.QWidget(Dialog)
        self.side_bar.setGeometry(QtCore.QRect(0, 0, 160, 721))
        self.side_bar.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.5);\n"
"")
        self.side_bar.setObjectName("side_bar")
        self.dash_btn = QtWidgets.QPushButton(self.side_bar)
        self.dash_btn.setGeometry(QtCore.QRect(10, 80, 140, 40))
        self.dash_btn.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dash_btn.setIcon(icon)
        self.dash_btn.setObjectName("dash_btn")
        self.appointment_btn = QtWidgets.QPushButton(self.side_bar)
        self.appointment_btn.setGeometry(QtCore.QRect(10, 480, 140, 40))
        self.appointment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Medico_modern/appointmentdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointment_btn.setIcon(icon1)
        self.appointment_btn.setObjectName("appointment_btn")
        self.dentist_btn = QtWidgets.QPushButton(self.side_bar)
        self.dentist_btn.setGeometry(QtCore.QRect(10, 580, 140, 40))
        self.dentist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Medico_modern/dentistimages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dentist_btn.setIcon(icon2)
        self.dentist_btn.setObjectName("dentist_btn")
        self.payment_btn = QtWidgets.QPushButton(self.side_bar)
        self.payment_btn.setGeometry(QtCore.QRect(10, 280, 140, 40))
        self.payment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Medico_modern/billingdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_btn.setIcon(icon3)
        self.payment_btn.setObjectName("payment_btn")
        self.expense_btn = QtWidgets.QPushButton(self.side_bar)
        self.expense_btn.setGeometry(QtCore.QRect(10, 380, 140, 40))
        self.expense_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.expense_btn.setIcon(icon3)
        self.expense_btn.setObjectName("expense_btn")
        self.label_4 = QtWidgets.QLabel(self.side_bar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.patient_btn = QtWidgets.QPushButton(self.side_bar)
        self.patient_btn.setGeometry(QtCore.QRect(10, 180, 140, 40))
        self.patient_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.patient_btn.setIcon(icon)
        self.patient_btn.setObjectName("patient_btn")
        self.calendarWidget = QtWidgets.QCalendarWidget(Dialog)
        self.calendarWidget.setGeometry(QtCore.QRect(210, 20, 401, 231))
        self.calendarWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.calendarWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgba(0, 0, 0,.85);\n"
"")
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.appointment_table = QtWidgets.QTableWidget(Dialog)
        self.appointment_table.setGeometry(QtCore.QRect(640, 50, 611, 201))
        self.appointment_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.appointment_table.setStyleSheet("alternate-background-color: rgba(255, 255, 255,.7);\n"
"selection-color: rgba(255, 255, 255,.5);\n"
"font: 12pt \"Segoe UI\";\n"
"background-color: rgba(255, 255, 255,.85);\n"
"border-left-color: rgba(255, 255, 255,.7);\n"
"selection-background-color: rgba(255, 255, 255,.7);\n"
"border-bottom-left-radius:20px;\n"
"border-top-color: rgba(255, 255, 255,.5);\n"
"border-bottom-right-radius:20px;\n"
"gridline-color: rgba(0, 0, 0,.4);")
        self.appointment_table.setObjectName("appointment_table")
        self.appointment_table.setColumnCount(6)
        self.appointment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.appointment_table.setHorizontalHeaderItem(5, item)
        self.expense_table = QtWidgets.QTableWidget(Dialog)
        self.expense_table.setGeometry(QtCore.QRect(210, 340, 441, 281))
        self.expense_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.expense_table.setStyleSheet("alternate-background-color: rgba(255, 255, 255,.7);\n"
"selection-color: rgba(255, 255, 255,.5);\n"
"font: 12pt \"Segoe UI\";\n"
"background-color: rgba(255, 255, 255,.85);\n"
"border-left-color: rgba(255, 255, 255,.7);\n"
"selection-background-color: rgba(255, 255, 255,.7);\n"
"border-bottom-left-radius:20px;\n"
"border-top-color: rgba(255, 255, 255,.5);\n"
"border-bottom-right-radius:20px;\n"
"gridline-color: rgba(0, 0, 0,.4);")
        self.expense_table.setObjectName("expense_table")
        self.expense_table.setColumnCount(3)
        self.expense_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.expense_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.expense_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.expense_table.setHorizontalHeaderItem(2, item)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 310, 441, 31))
        self.label.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(640, 20, 611, 31))
        self.label_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Images/ozkan-guner-aFqSRokmw2E-unsplash.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.payment_table = QtWidgets.QTableWidget(Dialog)
        self.payment_table.setGeometry(QtCore.QRect(680, 340, 571, 281))
        self.payment_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.payment_table.setStyleSheet("alternate-background-color: rgba(255, 255, 255,.7);\n"
"selection-color: rgba(255, 255, 255,.5);\n"
"font: 12pt \"Segoe UI\";\n"
"background-color: rgba(255, 255, 255,.85);\n"
"border-left-color: rgba(255, 255, 255,.7);\n"
"selection-background-color: rgba(255, 255, 255,.7);\n"
"border-bottom-left-radius:20px;\n"
"border-top-color: rgba(255, 255, 255,.5);\n"
"border-bottom-right-radius:20px;\n"
"gridline-color: rgba(0, 0, 0,.4);")
        self.payment_table.setObjectName("payment_table")
        self.payment_table.setColumnCount(4)
        self.payment_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.payment_table.setHorizontalHeaderItem(3, item)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(680, 310, 571, 31))
        self.label_5.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.label_5.setObjectName("label_5")
        self.print_appt = QtWidgets.QPushButton(Dialog)
        self.print_appt.setGeometry(QtCore.QRect(1100, 260, 140, 40))
        self.print_appt.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.print_appt.setIcon(icon)
        self.print_appt.setObjectName("print_appt")
        self.print_pay = QtWidgets.QPushButton(Dialog)
        self.print_pay.setGeometry(QtCore.QRect(1110, 630, 140, 40))
        self.print_pay.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.print_pay.setIcon(icon)
        self.print_pay.setObjectName("print_pay")
        self.print_expense = QtWidgets.QPushButton(Dialog)
        self.print_expense.setGeometry(QtCore.QRect(470, 630, 140, 40))
        self.print_expense.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.print_expense.setIcon(icon)
        self.print_expense.setObjectName("print_expense")
        self.label_3.raise_()
        self.side_bar.raise_()
        self.calendarWidget.raise_()
        self.appointment_table.raise_()
        self.expense_table.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.payment_table.raise_()
        self.label_5.raise_()
        self.print_appt.raise_()
        self.print_pay.raise_()
        self.print_expense.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.print_appt, self.print_expense)
        Dialog.setTabOrder(self.print_expense, self.print_pay)
        Dialog.setTabOrder(self.print_pay, self.dash_btn)
        Dialog.setTabOrder(self.dash_btn, self.patient_btn)
        Dialog.setTabOrder(self.patient_btn, self.payment_btn)
        Dialog.setTabOrder(self.payment_btn, self.expense_btn)
        Dialog.setTabOrder(self.expense_btn, self.appointment_btn)
        Dialog.setTabOrder(self.appointment_btn, self.dentist_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dash_btn.setText(_translate("Dialog", "Dashboard"))
        self.appointment_btn.setText(_translate("Dialog", "Appointments"))
        self.dentist_btn.setText(_translate("Dialog", "Dentists"))
        self.payment_btn.setText(_translate("Dialog", "Payments"))
        self.expense_btn.setText(_translate("Dialog", "Expense"))
        self.label_4.setText(_translate("Dialog", " Medico App "))
        self.patient_btn.setText(_translate("Dialog", "Patients"))
        item = self.appointment_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "First Name"))
        item = self.appointment_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Phone"))
        item = self.appointment_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Visit Time"))
        item = self.appointment_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Dentist Name"))
        item = self.appointment_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Patient ID"))
        item = self.appointment_table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Status"))
        item = self.expense_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Description"))
        item = self.expense_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Remarks"))
        item = self.expense_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Cost"))
        self.label.setText(_translate("Dialog", "Expenses of Today"))
        self.label_2.setText(_translate("Dialog", "Appointments of Today"))
        item = self.payment_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Patient ID"))
        item = self.payment_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "First Name"))
        item = self.payment_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Phone"))
        item = self.payment_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Payment"))
        self.label_5.setText(_translate("Dialog", "Payments of Today"))
        self.print_appt.setText(_translate("Dialog", "Print"))
        self.print_pay.setText(_translate("Dialog", "Print"))
        self.print_expense.setText(_translate("Dialog", "Print"))
