# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patients_custom_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 680)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.side_bar = QtWidgets.QWidget(Dialog)
        self.side_bar.setGeometry(QtCore.QRect(0, 0, 160, 681))
        self.side_bar.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.5);\n"
"")
        self.side_bar.setObjectName("side_bar")
        self.dash_btn = QtWidgets.QPushButton(self.side_bar)
        self.dash_btn.setGeometry(QtCore.QRect(10, 80, 140, 40))
        self.dash_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dash_btn.setIcon(icon)
        self.dash_btn.setObjectName("dash_btn")
        self.appointment_btn = QtWidgets.QPushButton(self.side_bar)
        self.appointment_btn.setGeometry(QtCore.QRect(10, 480, 140, 40))
        self.appointment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Medico_modern/appointmentdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointment_btn.setIcon(icon1)
        self.appointment_btn.setObjectName("appointment_btn")
        self.dentist_btn = QtWidgets.QPushButton(self.side_bar)
        self.dentist_btn.setGeometry(QtCore.QRect(10, 580, 140, 40))
        self.dentist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Medico_modern/dentistimages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dentist_btn.setIcon(icon2)
        self.dentist_btn.setObjectName("dentist_btn")
        self.payment_btn = QtWidgets.QPushButton(self.side_bar)
        self.payment_btn.setGeometry(QtCore.QRect(10, 280, 140, 40))
        self.payment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Medico_modern/billingdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_btn.setIcon(icon3)
        self.payment_btn.setObjectName("payment_btn")
        self.expense_btn = QtWidgets.QPushButton(self.side_bar)
        self.expense_btn.setGeometry(QtCore.QRect(10, 380, 140, 40))
        self.expense_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.expense_btn.setIcon(icon3)
        self.expense_btn.setObjectName("expense_btn")
        self.label_4 = QtWidgets.QLabel(self.side_bar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.patient_btn = QtWidgets.QPushButton(Dialog)
        self.patient_btn.setGeometry(QtCore.QRect(10, 180, 140, 40))
        self.patient_btn.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Medico_modern/patientdownload .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient_btn.setIcon(icon4)
        self.patient_btn.setObjectName("patient_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/daniel-frank-wKbWAMlHgNo-unsplash.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.f_name_labl = QtWidgets.QPushButton(Dialog)
        self.f_name_labl.setGeometry(QtCore.QRect(190, 50, 101, 31))
        self.f_name_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f_name_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.f_name_labl.setObjectName("f_name_labl")
        self.l_name_labl = QtWidgets.QPushButton(Dialog)
        self.l_name_labl.setGeometry(QtCore.QRect(455, 50, 111, 31))
        self.l_name_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.l_name_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.l_name_labl.setObjectName("l_name_labl")
        self.phn_labl = QtWidgets.QPushButton(Dialog)
        self.phn_labl.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.phn_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.phn_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.phn_labl.setObjectName("phn_labl")
        self.email_labl = QtWidgets.QPushButton(Dialog)
        self.email_labl.setGeometry(QtCore.QRect(455, 130, 111, 31))
        self.email_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.email_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.email_labl.setObjectName("email_labl")
        self.addr_labl = QtWidgets.QPushButton(Dialog)
        self.addr_labl.setGeometry(QtCore.QRect(190, 170, 101, 31))
        self.addr_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addr_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.addr_labl.setObjectName("addr_labl")
        self.occu_labl = QtWidgets.QPushButton(Dialog)
        self.occu_labl.setGeometry(QtCore.QRect(455, 170, 111, 31))
        self.occu_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.occu_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.occu_labl.setObjectName("occu_labl")
        self.refr_labl = QtWidgets.QPushButton(Dialog)
        self.refr_labl.setGeometry(QtCore.QRect(190, 210, 101, 31))
        self.refr_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.refr_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.refr_labl.setObjectName("refr_labl")
        self.depart_labl = QtWidgets.QPushButton(Dialog)
        self.depart_labl.setGeometry(QtCore.QRect(190, 320, 301, 31))
        self.depart_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.depart_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.depart_labl.setObjectName("depart_labl")
        self.comp_labl = QtWidgets.QPushButton(Dialog)
        self.comp_labl.setGeometry(QtCore.QRect(190, 360, 481, 31))
        self.comp_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comp_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.comp_labl.setObjectName("comp_labl")
        self.pat_id_labl = QtWidgets.QPushButton(Dialog)
        self.pat_id_labl.setGeometry(QtCore.QRect(455, 250, 111, 31))
        self.pat_id_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pat_id_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.pat_id_labl.setObjectName("pat_id_labl")
        self.age_labl = QtWidgets.QPushButton(Dialog)
        self.age_labl.setGeometry(QtCore.QRect(190, 130, 101, 31))
        self.age_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.age_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.age_labl.setObjectName("age_labl")
        self.gender_labl = QtWidgets.QPushButton(Dialog)
        self.gender_labl.setGeometry(QtCore.QRect(455, 90, 111, 31))
        self.gender_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gender_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.gender_labl.setObjectName("gender_labl")
        self.reg_dt_labl = QtWidgets.QPushButton(Dialog)
        self.reg_dt_labl.setGeometry(QtCore.QRect(455, 210, 111, 31))
        self.reg_dt_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.reg_dt_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.reg_dt_labl.setObjectName("reg_dt_labl")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(195, 625, 120, 30))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.return_btn = QtWidgets.QPushButton(Dialog)
        self.return_btn.setGeometry(QtCore.QRect(190, 620, 120, 30))
        self.return_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.return_btn.setObjectName("return_btn")
        self.next_btn = QtWidgets.QPushButton(Dialog)
        self.next_btn.setGeometry(QtCore.QRect(1125, 625, 120, 30))
        self.next_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.next_btn.setObjectName("next_btn")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(1130, 630, 120, 30))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.old_comp = QtWidgets.QTextBrowser(Dialog)
        self.old_comp.setGeometry(QtCore.QRect(190, 393, 481, 221))
        self.old_comp.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_comp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  10pt \"Segoe UI \";")
        self.old_comp.setObjectName("old_comp")
        self.age_labl_2 = QtWidgets.QPushButton(Dialog)
        self.age_labl_2.setGeometry(QtCore.QRect(730, 190, 101, 31))
        self.age_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.age_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.age_labl_2.setObjectName("age_labl_2")
        self.phn_labl_2 = QtWidgets.QPushButton(Dialog)
        self.phn_labl_2.setGeometry(QtCore.QRect(730, 140, 101, 31))
        self.phn_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.phn_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.phn_labl_2.setObjectName("phn_labl_2")
        self.l_name_labl_2 = QtWidgets.QPushButton(Dialog)
        self.l_name_labl_2.setGeometry(QtCore.QRect(730, 95, 101, 31))
        self.l_name_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.l_name_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.l_name_labl_2.setObjectName("l_name_labl_2")
        self.comp_labl_2 = QtWidgets.QPushButton(Dialog)
        self.comp_labl_2.setGeometry(QtCore.QRect(730, 360, 531, 31))
        self.comp_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comp_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.comp_labl_2.setObjectName("comp_labl_2")
        self.depart_labl_2 = QtWidgets.QPushButton(Dialog)
        self.depart_labl_2.setGeometry(QtCore.QRect(730, 320, 411, 31))
        self.depart_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.depart_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.depart_labl_2.setObjectName("depart_labl_2")
        self.refr_labl_2 = QtWidgets.QPushButton(Dialog)
        self.refr_labl_2.setGeometry(QtCore.QRect(730, 280, 101, 31))
        self.refr_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.refr_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.refr_labl_2.setObjectName("refr_labl_2")
        self.f_name_labl_2 = QtWidgets.QPushButton(Dialog)
        self.f_name_labl_2.setGeometry(QtCore.QRect(730, 50, 101, 31))
        self.f_name_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f_name_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.f_name_labl_2.setObjectName("f_name_labl_2")
        self.occu_labl_2 = QtWidgets.QPushButton(Dialog)
        self.occu_labl_2.setGeometry(QtCore.QRect(1020, 100, 111, 31))
        self.occu_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.occu_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.occu_labl_2.setObjectName("occu_labl_2")
        self.addr_labl_2 = QtWidgets.QPushButton(Dialog)
        self.addr_labl_2.setGeometry(QtCore.QRect(730, 235, 101, 31))
        self.addr_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addr_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.addr_labl_2.setObjectName("addr_labl_2")
        self.email_labl_2 = QtWidgets.QPushButton(Dialog)
        self.email_labl_2.setGeometry(QtCore.QRect(1020, 50, 111, 31))
        self.email_labl_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.email_labl_2.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.email_labl_2.setObjectName("email_labl_2")
        self.comp_labl_3 = QtWidgets.QPushButton(Dialog)
        self.comp_labl_3.setGeometry(QtCore.QRect(190, 10, 531, 31))
        self.comp_labl_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comp_labl_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.comp_labl_3.setObjectName("comp_labl_3")
        self.comp_labl_4 = QtWidgets.QPushButton(Dialog)
        self.comp_labl_4.setGeometry(QtCore.QRect(730, 10, 541, 31))
        self.comp_labl_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comp_labl_4.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.comp_labl_4.setObjectName("comp_labl_4")
        self.add_fname_edit = QtWidgets.QTextEdit(Dialog)
        self.add_fname_edit.setGeometry(QtCore.QRect(830, 50, 141, 31))
        self.add_fname_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_fname_edit.setObjectName("add_fname_edit")
        self.add_lname_edit = QtWidgets.QTextEdit(Dialog)
        self.add_lname_edit.setGeometry(QtCore.QRect(830, 95, 141, 31))
        self.add_lname_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_lname_edit.setObjectName("add_lname_edit")
        self.old_fname = QtWidgets.QLabel(Dialog)
        self.old_fname.setGeometry(QtCore.QRect(290, 50, 151, 31))
        self.old_fname.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_fname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_fname.setObjectName("old_fname")
        self.old_lname = QtWidgets.QLabel(Dialog)
        self.old_lname.setGeometry(QtCore.QRect(570, 50, 151, 31))
        self.old_lname.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_lname.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_lname.setObjectName("old_lname")
        self.old_phone = QtWidgets.QLabel(Dialog)
        self.old_phone.setGeometry(QtCore.QRect(290, 90, 151, 31))
        self.old_phone.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_phone.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_phone.setObjectName("old_phone")
        self.old_age = QtWidgets.QLabel(Dialog)
        self.old_age.setGeometry(QtCore.QRect(290, 130, 151, 31))
        self.old_age.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_age.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_age.setObjectName("old_age")
        self.old_address = QtWidgets.QLabel(Dialog)
        self.old_address.setGeometry(QtCore.QRect(290, 170, 151, 31))
        self.old_address.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_address.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_address.setObjectName("old_address")
        self.old_ref = QtWidgets.QLabel(Dialog)
        self.old_ref.setGeometry(QtCore.QRect(290, 210, 151, 31))
        self.old_ref.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_ref.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_ref.setObjectName("old_ref")
        self.gender = QtWidgets.QLabel(Dialog)
        self.gender.setGeometry(QtCore.QRect(570, 90, 151, 31))
        self.gender.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gender.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.gender.setObjectName("gender")
        self.old_email = QtWidgets.QLabel(Dialog)
        self.old_email.setGeometry(QtCore.QRect(570, 130, 151, 31))
        self.old_email.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_email.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_email.setObjectName("old_email")
        self.reg_date = QtWidgets.QLabel(Dialog)
        self.reg_date.setGeometry(QtCore.QRect(570, 210, 151, 31))
        self.reg_date.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.reg_date.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.reg_date.setObjectName("reg_date")
        self.old_job = QtWidgets.QLabel(Dialog)
        self.old_job.setGeometry(QtCore.QRect(570, 170, 151, 31))
        self.old_job.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_job.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_job.setObjectName("old_job")
        self.old_depart = QtWidgets.QLabel(Dialog)
        self.old_depart.setGeometry(QtCore.QRect(490, 320, 151, 31))
        self.old_depart.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.old_depart.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.old_depart.setObjectName("old_depart")
        self.updt_pat_id = QtWidgets.QPushButton(Dialog)
        self.updt_pat_id.setGeometry(QtCore.QRect(570, 250, 151, 31))
        self.updt_pat_id.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.updt_pat_id.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";")
        self.updt_pat_id.setObjectName("updt_pat_id")
        self.address_combo = QtWidgets.QComboBox(Dialog)
        self.address_combo.setGeometry(QtCore.QRect(830, 235, 141, 30))
        self.address_combo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";")
        self.address_combo.setObjectName("address_combo")
        self.address_combo.addItem("")
        self.address_combo.setItemText(0, "")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.address_combo.addItem("")
        self.add_phn_edit = QtWidgets.QTextEdit(Dialog)
        self.add_phn_edit.setGeometry(QtCore.QRect(830, 140, 141, 31))
        self.add_phn_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_phn_edit.setObjectName("add_phn_edit")
        self.add_age_edit = QtWidgets.QTextEdit(Dialog)
        self.add_age_edit.setGeometry(QtCore.QRect(830, 190, 141, 31))
        self.add_age_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_age_edit.setObjectName("add_age_edit")
        self.add_ref_edit = QtWidgets.QTextEdit(Dialog)
        self.add_ref_edit.setGeometry(QtCore.QRect(830, 280, 141, 31))
        self.add_ref_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_ref_edit.setObjectName("add_ref_edit")
        self.add_email_edit = QtWidgets.QTextEdit(Dialog)
        self.add_email_edit.setGeometry(QtCore.QRect(1130, 50, 141, 31))
        self.add_email_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_email_edit.setObjectName("add_email_edit")
        self.add_occu_edit = QtWidgets.QTextEdit(Dialog)
        self.add_occu_edit.setGeometry(QtCore.QRect(1130, 100, 141, 31))
        self.add_occu_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_occu_edit.setObjectName("add_occu_edit")
        self.add_depart_edit = QtWidgets.QTextEdit(Dialog)
        self.add_depart_edit.setGeometry(QtCore.QRect(1140, 320, 141, 31))
        self.add_depart_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_depart_edit.setObjectName("add_depart_edit")
        self.add_complain_edit = QtWidgets.QTextEdit(Dialog)
        self.add_complain_edit.setGeometry(QtCore.QRect(730, 390, 531, 221))
        self.add_complain_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.add_complain_edit.setObjectName("add_complain_edit")
        self.label.raise_()
        self.side_bar.raise_()
        self.patient_btn.raise_()
        self.f_name_labl.raise_()
        self.l_name_labl.raise_()
        self.phn_labl.raise_()
        self.email_labl.raise_()
        self.addr_labl.raise_()
        self.occu_labl.raise_()
        self.refr_labl.raise_()
        self.depart_labl.raise_()
        self.comp_labl.raise_()
        self.pat_id_labl.raise_()
        self.age_labl.raise_()
        self.gender_labl.raise_()
        self.reg_dt_labl.raise_()
        self.label_6.raise_()
        self.return_btn.raise_()
        self.label_8.raise_()
        self.next_btn.raise_()
        self.old_comp.raise_()
        self.age_labl_2.raise_()
        self.phn_labl_2.raise_()
        self.l_name_labl_2.raise_()
        self.comp_labl_2.raise_()
        self.depart_labl_2.raise_()
        self.refr_labl_2.raise_()
        self.f_name_labl_2.raise_()
        self.occu_labl_2.raise_()
        self.addr_labl_2.raise_()
        self.email_labl_2.raise_()
        self.comp_labl_3.raise_()
        self.comp_labl_4.raise_()
        self.add_fname_edit.raise_()
        self.add_lname_edit.raise_()
        self.old_fname.raise_()
        self.old_lname.raise_()
        self.old_phone.raise_()
        self.old_age.raise_()
        self.old_address.raise_()
        self.old_ref.raise_()
        self.gender.raise_()
        self.old_email.raise_()
        self.reg_date.raise_()
        self.old_job.raise_()
        self.old_depart.raise_()
        self.updt_pat_id.raise_()
        self.address_combo.raise_()
        self.add_phn_edit.raise_()
        self.add_age_edit.raise_()
        self.add_ref_edit.raise_()
        self.add_email_edit.raise_()
        self.add_occu_edit.raise_()
        self.add_depart_edit.raise_()
        self.add_complain_edit.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.add_fname_edit, self.add_lname_edit)
        Dialog.setTabOrder(self.add_lname_edit, self.add_phn_edit)
        Dialog.setTabOrder(self.add_phn_edit, self.add_age_edit)
        Dialog.setTabOrder(self.add_age_edit, self.address_combo)
        Dialog.setTabOrder(self.address_combo, self.add_ref_edit)
        Dialog.setTabOrder(self.add_ref_edit, self.add_email_edit)
        Dialog.setTabOrder(self.add_email_edit, self.add_occu_edit)
        Dialog.setTabOrder(self.add_occu_edit, self.add_depart_edit)
        Dialog.setTabOrder(self.add_depart_edit, self.add_complain_edit)
        Dialog.setTabOrder(self.add_complain_edit, self.next_btn)
        Dialog.setTabOrder(self.next_btn, self.return_btn)
        Dialog.setTabOrder(self.return_btn, self.dash_btn)
        Dialog.setTabOrder(self.dash_btn, self.patient_btn)
        Dialog.setTabOrder(self.patient_btn, self.payment_btn)
        Dialog.setTabOrder(self.payment_btn, self.expense_btn)
        Dialog.setTabOrder(self.expense_btn, self.appointment_btn)
        Dialog.setTabOrder(self.appointment_btn, self.dentist_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dash_btn.setText(_translate("Dialog", "Dashboard"))
        self.appointment_btn.setText(_translate("Dialog", "Appointments"))
        self.dentist_btn.setText(_translate("Dialog", "Dentists"))
        self.payment_btn.setText(_translate("Dialog", "Payments"))
        self.expense_btn.setText(_translate("Dialog", "Expense"))
        self.label_4.setText(_translate("Dialog", " Medico App "))
        self.patient_btn.setText(_translate("Dialog", "Patients"))
        self.f_name_labl.setText(_translate("Dialog", "First Name:"))
        self.l_name_labl.setText(_translate("Dialog", "Last Name:"))
        self.phn_labl.setText(_translate("Dialog", "Phone:"))
        self.email_labl.setText(_translate("Dialog", "Email:"))
        self.addr_labl.setText(_translate("Dialog", "Address:"))
        self.occu_labl.setText(_translate("Dialog", "Occupation:"))
        self.refr_labl.setText(_translate("Dialog", "Reference:"))
        self.depart_labl.setText(_translate("Dialog", "(If lives abroad) Date of Departure:"))
        self.comp_labl.setText(_translate("Dialog", "Complain:"))
        self.pat_id_labl.setText(_translate("Dialog", "Patient ID:"))
        self.age_labl.setText(_translate("Dialog", "Age:"))
        self.gender_labl.setText(_translate("Dialog", "Gender:"))
        self.reg_dt_labl.setText(_translate("Dialog", "Date of Reg:"))
        self.return_btn.setText(_translate("Dialog", "Return"))
        self.next_btn.setText(_translate("Dialog", "Next"))
        self.old_comp.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI \'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.age_labl_2.setText(_translate("Dialog", "Age:"))
        self.phn_labl_2.setText(_translate("Dialog", "Phone:"))
        self.l_name_labl_2.setText(_translate("Dialog", "Last Name:"))
        self.comp_labl_2.setText(_translate("Dialog", "Complain:"))
        self.depart_labl_2.setText(_translate("Dialog", "(If lives abroad) Date of Departure(mm/dd/yyyy):"))
        self.refr_labl_2.setText(_translate("Dialog", "Reference:"))
        self.f_name_labl_2.setText(_translate("Dialog", "First Name:"))
        self.occu_labl_2.setText(_translate("Dialog", "Occupation:"))
        self.addr_labl_2.setText(_translate("Dialog", "Address:"))
        self.email_labl_2.setText(_translate("Dialog", "Email:"))
        self.comp_labl_3.setText(_translate("Dialog", "Old Information:"))
        self.comp_labl_4.setText(_translate("Dialog", "New Information"))
        self.old_fname.setText(_translate("Dialog", "N/A"))
        self.old_lname.setText(_translate("Dialog", "N/A"))
        self.old_phone.setText(_translate("Dialog", "N/A"))
        self.old_age.setText(_translate("Dialog", "N/A"))
        self.old_address.setText(_translate("Dialog", "N/A"))
        self.old_ref.setText(_translate("Dialog", "N/A"))
        self.gender.setText(_translate("Dialog", "N/A"))
        self.old_email.setText(_translate("Dialog", "N/A"))
        self.reg_date.setText(_translate("Dialog", "N/A"))
        self.old_job.setText(_translate("Dialog", "N/A"))
        self.old_depart.setText(_translate("Dialog", "N/A"))
        self.updt_pat_id.setText(_translate("Dialog", "N/A"))
        self.address_combo.setItemText(1, _translate("Dialog", "Abdullahpur"))
        self.address_combo.setItemText(2, _translate("Dialog", "Adabor"))
        self.address_combo.setItemText(3, _translate("Dialog", "Agargaon"))
        self.address_combo.setItemText(4, _translate("Dialog", "Ahmadbag"))
        self.address_combo.setItemText(5, _translate("Dialog", "Badda"))
        self.address_combo.setItemText(6, _translate("Dialog", "Baganbari"))
        self.address_combo.setItemText(7, _translate("Dialog", "Banani"))
        self.address_combo.setItemText(8, _translate("Dialog", "Baridhara"))
        self.address_combo.setItemText(9, _translate("Dialog", "Basaboo"))
        self.address_combo.setItemText(10, _translate("Dialog", "Bashundhara"))
        self.address_combo.setItemText(11, _translate("Dialog", "Banasree"))
        self.address_combo.setItemText(12, _translate("Dialog", "Bawnia"))
        self.address_combo.setItemText(13, _translate("Dialog", "Beraid"))
        self.address_combo.setItemText(14, _translate("Dialog", "Bochila"))
        self.address_combo.setItemText(15, _translate("Dialog", "BRAC Bank"))
        self.address_combo.setItemText(16, _translate("Dialog", "Cantonment area"))
        self.address_combo.setItemText(17, _translate("Dialog", "Dakkhin Gao"))
        self.address_combo.setItemText(18, _translate("Dialog", "Dakshinkhan"))
        self.address_combo.setItemText(19, _translate("Dialog", "Dania"))
        self.address_combo.setItemText(20, _translate("Dialog", "Demra"))
        self.address_combo.setItemText(21, _translate("Dialog", "Dhanmondi"))
        self.address_combo.setItemText(22, _translate("Dialog", "Farmgate"))
        self.address_combo.setItemText(23, _translate("Dialog", "Gabtali"))
        self.address_combo.setItemText(24, _translate("Dialog", "Goran"))
        self.address_combo.setItemText(25, _translate("Dialog", "Gulshan"))
        self.address_combo.setItemText(26, _translate("Dialog", "Hazaribagh"))
        self.address_combo.setItemText(27, _translate("Dialog", "Islampur"))
        self.address_combo.setItemText(28, _translate("Dialog", "Jurain"))
        self.address_combo.setItemText(29, _translate("Dialog", "Kadamtala"))
        self.address_combo.setItemText(30, _translate("Dialog", "Kafrul"))
        self.address_combo.setItemText(31, _translate("Dialog", "Kakrail"))
        self.address_combo.setItemText(32, _translate("Dialog", "Kamalapur"))
        self.address_combo.setItemText(33, _translate("Dialog", "Kamrangirchar"))
        self.address_combo.setItemText(34, _translate("Dialog", "Kazipara"))
        self.address_combo.setItemText(35, _translate("Dialog", "Khilgaon"))
        self.address_combo.setItemText(36, _translate("Dialog", "Khilkhet"))
        self.address_combo.setItemText(37, _translate("Dialog", "Kotwali"))
        self.address_combo.setItemText(38, _translate("Dialog", "Lalbagh"))
        self.address_combo.setItemText(39, _translate("Dialog", "Madartek"))
        self.address_combo.setItemText(40, _translate("Dialog", "Manda"))
        self.address_combo.setItemText(41, _translate("Dialog", "Manikdi"))
        self.address_combo.setItemText(42, _translate("Dialog", "Matuail"))
        self.address_combo.setItemText(43, _translate("Dialog", "Mayakanon"))
        self.address_combo.setItemText(44, _translate("Dialog", "Mohakhali"))
        self.address_combo.setItemText(45, _translate("Dialog", "Mohammadpur"))
        self.address_combo.setItemText(46, _translate("Dialog", "Motijheel"))
        self.address_combo.setItemText(47, _translate("Dialog", "Mirpur"))
        self.address_combo.setItemText(48, _translate("Dialog", "Mugda"))
        self.address_combo.setItemText(49, _translate("Dialog", "Nandipara"))
        self.address_combo.setItemText(50, _translate("Dialog", "Niketan, Gulshan"))
        self.address_combo.setItemText(51, _translate("Dialog", "Nimtoli"))
        self.address_combo.setItemText(52, _translate("Dialog", "Outter Dhaka"))
        self.address_combo.setItemText(53, _translate("Dialog", "Pallabi"))
        self.address_combo.setItemText(54, _translate("Dialog", "Paltan"))
        self.address_combo.setItemText(55, _translate("Dialog", "Paribagh"))
        self.address_combo.setItemText(56, _translate("Dialog", "Rajarbag"))
        self.address_combo.setItemText(57, _translate("Dialog", "Ramna"))
        self.address_combo.setItemText(58, _translate("Dialog", "Rampura"))
        self.address_combo.setItemText(59, _translate("Dialog", "Sabujbag"))
        self.address_combo.setItemText(60, _translate("Dialog", "Sadarghat"))
        self.address_combo.setItemText(61, _translate("Dialog", "Satarkul"))
        self.address_combo.setItemText(62, _translate("Dialog", "Segunbagicha"))
        self.address_combo.setItemText(63, _translate("Dialog", "Shahbagh"))
        self.address_combo.setItemText(64, _translate("Dialog", "Sher-e-Bangla Nagar"))
        self.address_combo.setItemText(65, _translate("Dialog", "Shyampur"))
        self.address_combo.setItemText(66, _translate("Dialog", "Sutrapur"))
        self.address_combo.setItemText(67, _translate("Dialog", "Tejgaon"))
        self.address_combo.setItemText(68, _translate("Dialog", "UCBL Bank"))
        self.address_combo.setItemText(69, _translate("Dialog", "Uttara"))
        self.address_combo.setItemText(70, _translate("Dialog", "Uttarkhan"))
        self.address_combo.setItemText(71, _translate("Dialog", "Vatara"))
        self.address_combo.setItemText(72, _translate("Dialog", "Wari"))
