# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patients_window_detailed.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 680)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.side_bar = QtWidgets.QWidget(Dialog)
        self.side_bar.setGeometry(QtCore.QRect(0, 0, 160, 681))
        self.side_bar.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.5);\n"
"")
        self.side_bar.setObjectName("side_bar")
        self.dash_btn = QtWidgets.QPushButton(self.side_bar)
        self.dash_btn.setGeometry(QtCore.QRect(10, 80, 140, 40))
        self.dash_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dash_btn.setIcon(icon)
        self.dash_btn.setObjectName("dash_btn")
        self.appointment_btn = QtWidgets.QPushButton(self.side_bar)
        self.appointment_btn.setGeometry(QtCore.QRect(10, 480, 140, 40))
        self.appointment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Medico_modern/appointmentdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointment_btn.setIcon(icon1)
        self.appointment_btn.setObjectName("appointment_btn")
        self.dentist_btn = QtWidgets.QPushButton(self.side_bar)
        self.dentist_btn.setGeometry(QtCore.QRect(10, 580, 140, 40))
        self.dentist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Medico_modern/dentistimages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dentist_btn.setIcon(icon2)
        self.dentist_btn.setObjectName("dentist_btn")
        self.payment_btn = QtWidgets.QPushButton(self.side_bar)
        self.payment_btn.setGeometry(QtCore.QRect(10, 280, 140, 40))
        self.payment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Medico_modern/billingdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_btn.setIcon(icon3)
        self.payment_btn.setObjectName("payment_btn")
        self.expense_btn = QtWidgets.QPushButton(self.side_bar)
        self.expense_btn.setGeometry(QtCore.QRect(10, 380, 140, 40))
        self.expense_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.expense_btn.setIcon(icon3)
        self.expense_btn.setObjectName("expense_btn")
        self.label_4 = QtWidgets.QLabel(self.side_bar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.label_4.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"text-decoration: underline;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.patient_btn = QtWidgets.QPushButton(Dialog)
        self.patient_btn.setGeometry(QtCore.QRect(10, 180, 140, 40))
        self.patient_btn.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Medico_modern/patientdownload .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient_btn.setIcon(icon4)
        self.patient_btn.setObjectName("patient_btn")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(700, 30, 551, 521))
        self.widget.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgba(0, 0, 0,.5);\n"
"color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.q1 = QtWidgets.QLabel(self.widget)
        self.q1.setGeometry(QtCore.QRect(10, 40, 481, 20))
        self.q1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.q1.setObjectName("q1")
        self.q2 = QtWidgets.QLabel(self.widget)
        self.q2.setGeometry(QtCore.QRect(10, 70, 481, 20))
        self.q2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q2.setObjectName("q2")
        self.q3 = QtWidgets.QLabel(self.widget)
        self.q3.setGeometry(QtCore.QRect(10, 100, 481, 20))
        self.q3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q3.setObjectName("q3")
        self.q4 = QtWidgets.QLabel(self.widget)
        self.q4.setGeometry(QtCore.QRect(10, 130, 481, 20))
        self.q4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q4.setObjectName("q4")
        self.q5 = QtWidgets.QLabel(self.widget)
        self.q5.setGeometry(QtCore.QRect(10, 160, 481, 20))
        self.q5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q5.setObjectName("q5")
        self.q6 = QtWidgets.QLabel(self.widget)
        self.q6.setGeometry(QtCore.QRect(10, 190, 481, 20))
        self.q6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q6.setObjectName("q6")
        self.q7 = QtWidgets.QLabel(self.widget)
        self.q7.setGeometry(QtCore.QRect(10, 220, 481, 20))
        self.q7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q7.setObjectName("q7")
        self.q8 = QtWidgets.QLabel(self.widget)
        self.q8.setGeometry(QtCore.QRect(10, 250, 481, 20))
        self.q8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q8.setObjectName("q8")
        self.q9 = QtWidgets.QLabel(self.widget)
        self.q9.setGeometry(QtCore.QRect(10, 280, 481, 20))
        self.q9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q9.setObjectName("q9")
        self.q10 = QtWidgets.QLabel(self.widget)
        self.q10.setGeometry(QtCore.QRect(10, 310, 481, 20))
        self.q10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q10.setObjectName("q10")
        self.q11 = QtWidgets.QLabel(self.widget)
        self.q11.setGeometry(QtCore.QRect(10, 340, 481, 20))
        self.q11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q11.setObjectName("q11")
        self.q12 = QtWidgets.QLabel(self.widget)
        self.q12.setGeometry(QtCore.QRect(10, 370, 481, 20))
        self.q12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q12.setObjectName("q12")
        self.q13 = QtWidgets.QLabel(self.widget)
        self.q13.setGeometry(QtCore.QRect(10, 400, 481, 20))
        self.q13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q13.setObjectName("q13")
        self.q14 = QtWidgets.QLabel(self.widget)
        self.q14.setGeometry(QtCore.QRect(10, 430, 481, 20))
        self.q14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q14.setObjectName("q14")
        self.q15 = QtWidgets.QLabel(self.widget)
        self.q15.setGeometry(QtCore.QRect(10, 460, 481, 20))
        self.q15.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q15.setObjectName("q15")
        self.q16 = QtWidgets.QLabel(self.widget)
        self.q16.setGeometry(QtCore.QRect(10, 490, 481, 20))
        self.q16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.q16.setObjectName("q16")
        self.findings_label_2 = QtWidgets.QLabel(self.widget)
        self.findings_label_2.setGeometry(QtCore.QRect(0, 0, 551, 31))
        self.findings_label_2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);")
        self.findings_label_2.setObjectName("findings_label_2")
        self.updt_q1 = QtWidgets.QLabel(self.widget)
        self.updt_q1.setGeometry(QtCore.QRect(496, 40, 45, 20))
        self.updt_q1.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q1.setObjectName("updt_q1")
        self.updt_q2 = QtWidgets.QLabel(self.widget)
        self.updt_q2.setGeometry(QtCore.QRect(496, 70, 45, 20))
        self.updt_q2.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q2.setObjectName("updt_q2")
        self.updt_q3 = QtWidgets.QLabel(self.widget)
        self.updt_q3.setGeometry(QtCore.QRect(496, 100, 45, 20))
        self.updt_q3.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q3.setObjectName("updt_q3")
        self.updt_q4 = QtWidgets.QLabel(self.widget)
        self.updt_q4.setGeometry(QtCore.QRect(496, 130, 45, 20))
        self.updt_q4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q4.setObjectName("updt_q4")
        self.updt_q5 = QtWidgets.QLabel(self.widget)
        self.updt_q5.setGeometry(QtCore.QRect(496, 160, 45, 20))
        self.updt_q5.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q5.setObjectName("updt_q5")
        self.updt_q6 = QtWidgets.QLabel(self.widget)
        self.updt_q6.setGeometry(QtCore.QRect(496, 190, 45, 20))
        self.updt_q6.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q6.setObjectName("updt_q6")
        self.updt_q7 = QtWidgets.QLabel(self.widget)
        self.updt_q7.setGeometry(QtCore.QRect(496, 220, 45, 20))
        self.updt_q7.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q7.setObjectName("updt_q7")
        self.updt_q8 = QtWidgets.QLabel(self.widget)
        self.updt_q8.setGeometry(QtCore.QRect(496, 250, 45, 20))
        self.updt_q8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q8.setObjectName("updt_q8")
        self.updt_q9 = QtWidgets.QLabel(self.widget)
        self.updt_q9.setGeometry(QtCore.QRect(496, 280, 45, 20))
        self.updt_q9.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q9.setObjectName("updt_q9")
        self.updt_q10 = QtWidgets.QLabel(self.widget)
        self.updt_q10.setGeometry(QtCore.QRect(496, 310, 45, 20))
        self.updt_q10.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q10.setObjectName("updt_q10")
        self.updt_q11 = QtWidgets.QLabel(self.widget)
        self.updt_q11.setGeometry(QtCore.QRect(496, 340, 45, 20))
        self.updt_q11.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q11.setObjectName("updt_q11")
        self.updt_q12 = QtWidgets.QLabel(self.widget)
        self.updt_q12.setGeometry(QtCore.QRect(496, 370, 45, 20))
        self.updt_q12.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q12.setObjectName("updt_q12")
        self.updt_q13 = QtWidgets.QLabel(self.widget)
        self.updt_q13.setGeometry(QtCore.QRect(496, 400, 45, 20))
        self.updt_q13.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q13.setObjectName("updt_q13")
        self.updt_q14 = QtWidgets.QLabel(self.widget)
        self.updt_q14.setGeometry(QtCore.QRect(496, 430, 45, 20))
        self.updt_q14.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q14.setObjectName("updt_q14")
        self.updt_q15 = QtWidgets.QLabel(self.widget)
        self.updt_q15.setGeometry(QtCore.QRect(496, 460, 45, 20))
        self.updt_q15.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q15.setObjectName("updt_q15")
        self.updt_q16 = QtWidgets.QLabel(self.widget)
        self.updt_q16.setGeometry(QtCore.QRect(496, 490, 45, 20))
        self.updt_q16.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.updt_q16.setObjectName("updt_q16")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -7, 1280, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/daniel-frank-wKbWAMlHgNo-unsplash.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.f_name_labl = QtWidgets.QPushButton(Dialog)
        self.f_name_labl.setGeometry(QtCore.QRect(190, 10, 101, 31))
        self.f_name_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f_name_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.f_name_labl.setObjectName("f_name_labl")
        self.updt_f_name = QtWidgets.QPushButton(Dialog)
        self.updt_f_name.setGeometry(QtCore.QRect(290, 10, 151, 31))
        self.updt_f_name.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_f_name.setObjectName("updt_f_name")
        self.l_name_labl = QtWidgets.QPushButton(Dialog)
        self.l_name_labl.setGeometry(QtCore.QRect(457, 10, 111, 31))
        self.l_name_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.l_name_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.l_name_labl.setObjectName("l_name_labl")
        self.updt_l_name = QtWidgets.QPushButton(Dialog)
        self.updt_l_name.setGeometry(QtCore.QRect(570, 10, 101, 31))
        self.updt_l_name.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_l_name.setObjectName("updt_l_name")
        self.phn_labl = QtWidgets.QPushButton(Dialog)
        self.phn_labl.setGeometry(QtCore.QRect(190, 90, 101, 31))
        self.phn_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.phn_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.phn_labl.setObjectName("phn_labl")
        self.email_labl = QtWidgets.QPushButton(Dialog)
        self.email_labl.setGeometry(QtCore.QRect(457, 90, 111, 31))
        self.email_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.email_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.email_labl.setObjectName("email_labl")
        self.updt_phn = QtWidgets.QPushButton(Dialog)
        self.updt_phn.setGeometry(QtCore.QRect(290, 90, 151, 31))
        self.updt_phn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_phn.setObjectName("updt_phn")
        self.updt_email = QtWidgets.QPushButton(Dialog)
        self.updt_email.setGeometry(QtCore.QRect(570, 90, 101, 31))
        self.updt_email.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_email.setObjectName("updt_email")
        self.updt_addr = QtWidgets.QPushButton(Dialog)
        self.updt_addr.setGeometry(QtCore.QRect(290, 170, 151, 31))
        self.updt_addr.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_addr.setObjectName("updt_addr")
        self.addr_labl = QtWidgets.QPushButton(Dialog)
        self.addr_labl.setGeometry(QtCore.QRect(190, 170, 101, 31))
        self.addr_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.addr_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.addr_labl.setObjectName("addr_labl")
        self.updt_occu = QtWidgets.QPushButton(Dialog)
        self.updt_occu.setGeometry(QtCore.QRect(570, 170, 101, 31))
        self.updt_occu.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_occu.setObjectName("updt_occu")
        self.updt_refr = QtWidgets.QPushButton(Dialog)
        self.updt_refr.setGeometry(QtCore.QRect(290, 210, 151, 31))
        self.updt_refr.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_refr.setObjectName("updt_refr")
        self.occu_labl = QtWidgets.QPushButton(Dialog)
        self.occu_labl.setGeometry(QtCore.QRect(457, 170, 111, 31))
        self.occu_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.occu_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.occu_labl.setObjectName("occu_labl")
        self.refr_labl = QtWidgets.QPushButton(Dialog)
        self.refr_labl.setGeometry(QtCore.QRect(190, 210, 101, 31))
        self.refr_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.refr_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.refr_labl.setObjectName("refr_labl")
        self.depart_labl = QtWidgets.QPushButton(Dialog)
        self.depart_labl.setGeometry(QtCore.QRect(190, 251, 301, 31))
        self.depart_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.depart_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.depart_labl.setObjectName("depart_labl")
        self.updt_depart = QtWidgets.QPushButton(Dialog)
        self.updt_depart.setGeometry(QtCore.QRect(490, 251, 181, 31))
        self.updt_depart.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_depart.setObjectName("updt_depart")
        self.comp_labl = QtWidgets.QPushButton(Dialog)
        self.comp_labl.setGeometry(QtCore.QRect(190, 297, 481, 31))
        self.comp_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comp_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.comp_labl.setObjectName("comp_labl")
        self.pat_id_labl = QtWidgets.QPushButton(Dialog)
        self.pat_id_labl.setGeometry(QtCore.QRect(190, 50, 101, 31))
        self.pat_id_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pat_id_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.pat_id_labl.setObjectName("pat_id_labl")
        self.updt_pat_id = QtWidgets.QPushButton(Dialog)
        self.updt_pat_id.setGeometry(QtCore.QRect(290, 50, 151, 31))
        self.updt_pat_id.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_pat_id.setObjectName("updt_pat_id")
        self.age_labl = QtWidgets.QPushButton(Dialog)
        self.age_labl.setGeometry(QtCore.QRect(190, 130, 101, 31))
        self.age_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.age_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.age_labl.setObjectName("age_labl")
        self.updt_age = QtWidgets.QPushButton(Dialog)
        self.updt_age.setGeometry(QtCore.QRect(290, 130, 151, 31))
        self.updt_age.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_age.setObjectName("updt_age")
        self.gender_labl = QtWidgets.QPushButton(Dialog)
        self.gender_labl.setGeometry(QtCore.QRect(457, 51, 111, 31))
        self.gender_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gender_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.gender_labl.setObjectName("gender_labl")
        self.updt_gender = QtWidgets.QPushButton(Dialog)
        self.updt_gender.setGeometry(QtCore.QRect(570, 51, 101, 31))
        self.updt_gender.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_gender.setObjectName("updt_gender")
        self.reg_dt_labl = QtWidgets.QPushButton(Dialog)
        self.reg_dt_labl.setGeometry(QtCore.QRect(457, 130, 111, 31))
        self.reg_dt_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.reg_dt_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.reg_dt_labl.setObjectName("reg_dt_labl")
        self.updt_reg_dt = QtWidgets.QPushButton(Dialog)
        self.updt_reg_dt.setGeometry(QtCore.QRect(570, 130, 101, 31))
        self.updt_reg_dt.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_reg_dt.setObjectName("updt_reg_dt")
        self.findings_label = QtWidgets.QPushButton(Dialog)
        self.findings_label.setGeometry(QtCore.QRect(190, 440, 481, 31))
        self.findings_label.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.findings_label.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.findings_label.setObjectName("findings_label")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(200, 625, 120, 30))
        self.label_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.return_pat = QtWidgets.QPushButton(Dialog)
        self.return_pat.setGeometry(QtCore.QRect(195, 620, 120, 30))
        self.return_pat.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.return_pat.setObjectName("return_pat")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(1135, 625, 120, 30))
        self.label_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.delete_pat = QtWidgets.QPushButton(Dialog)
        self.delete_pat.setGeometry(QtCore.QRect(1130, 620, 120, 30))
        self.delete_pat.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"    color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 0, 0);\n"
"    background-color: rgb(255, 85, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(255, 0, 0);\n"
"    background-color: rgb(255, 85, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.delete_pat.setObjectName("delete_pat")
        self.updt_med_findings = QtWidgets.QTextBrowser(Dialog)
        self.updt_med_findings.setGeometry(QtCore.QRect(190, 470, 481, 110))
        self.updt_med_findings.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  10pt \"Segoe UI \";\n"
"}\n"
"QTextBrowser:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_med_findings.setObjectName("updt_med_findings")
        self.customize_btn = QtWidgets.QPushButton(Dialog)
        self.customize_btn.setGeometry(QtCore.QRect(990, 620, 120, 30))
        self.customize_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.customize_btn.setObjectName("customize_btn")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(995, 625, 120, 30))
        self.label_7.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.new_file_btn = QtWidgets.QPushButton(Dialog)
        self.new_file_btn.setGeometry(QtCore.QRect(845, 620, 120, 30))
        self.new_file_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.new_file_btn.setObjectName("new_file_btn")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(850, 625, 120, 30))
        self.label_8.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.updt_comp = QtWidgets.QTextBrowser(Dialog)
        self.updt_comp.setGeometry(QtCore.QRect(190, 330, 481, 101))
        self.updt_comp.setStyleSheet("QTextBrowser{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  10pt \"Segoe UI \";\n"
"}\n"
"QTextBrowser:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_comp.setObjectName("updt_comp")
        self.file_name_labl = QtWidgets.QPushButton(Dialog)
        self.file_name_labl.setGeometry(QtCore.QRect(457, 210, 111, 31))
        self.file_name_labl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.file_name_labl.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.file_name_labl.setObjectName("file_name_labl")
        self.updt_file_name = QtWidgets.QPushButton(Dialog)
        self.updt_file_name.setGeometry(QtCore.QRect(570, 210, 101, 31))
        self.updt_file_name.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font:  12pt \"Segoe UI \";\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_file_name.setObjectName("updt_file_name")
        self.updt_file_btn = QtWidgets.QPushButton(Dialog)
        self.updt_file_btn.setGeometry(QtCore.QRect(695, 620, 120, 30))
        self.updt_file_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.updt_file_btn.setObjectName("updt_file_btn")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(700, 625, 120, 30))
        self.label_9.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(525, 625, 150, 30))
        self.label_10.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.pay_hist_btn = QtWidgets.QPushButton(Dialog)
        self.pay_hist_btn.setGeometry(QtCore.QRect(520, 620, 150, 30))
        self.pay_hist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pay_hist_btn.setObjectName("pay_hist_btn")
        self.files_hist_btn = QtWidgets.QPushButton(Dialog)
        self.files_hist_btn.setGeometry(QtCore.QRect(345, 620, 150, 30))
        self.files_hist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus {\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.files_hist_btn.setObjectName("files_hist_btn")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(350, 625, 150, 30))
        self.label_11.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label.raise_()
        self.side_bar.raise_()
        self.patient_btn.raise_()
        self.widget.raise_()
        self.f_name_labl.raise_()
        self.updt_f_name.raise_()
        self.l_name_labl.raise_()
        self.updt_l_name.raise_()
        self.phn_labl.raise_()
        self.email_labl.raise_()
        self.updt_phn.raise_()
        self.updt_email.raise_()
        self.updt_addr.raise_()
        self.addr_labl.raise_()
        self.updt_occu.raise_()
        self.updt_refr.raise_()
        self.occu_labl.raise_()
        self.refr_labl.raise_()
        self.depart_labl.raise_()
        self.updt_depart.raise_()
        self.comp_labl.raise_()
        self.pat_id_labl.raise_()
        self.updt_pat_id.raise_()
        self.age_labl.raise_()
        self.updt_age.raise_()
        self.gender_labl.raise_()
        self.updt_gender.raise_()
        self.reg_dt_labl.raise_()
        self.updt_reg_dt.raise_()
        self.findings_label.raise_()
        self.label_6.raise_()
        self.return_pat.raise_()
        self.label_5.raise_()
        self.delete_pat.raise_()
        self.updt_med_findings.raise_()
        self.label_7.raise_()
        self.customize_btn.raise_()
        self.label_8.raise_()
        self.new_file_btn.raise_()
        self.updt_comp.raise_()
        self.file_name_labl.raise_()
        self.updt_file_name.raise_()
        self.label_9.raise_()
        self.updt_file_btn.raise_()
        self.label_10.raise_()
        self.pay_hist_btn.raise_()
        self.label_11.raise_()
        self.files_hist_btn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.patient_btn, self.payment_btn)
        Dialog.setTabOrder(self.payment_btn, self.expense_btn)
        Dialog.setTabOrder(self.expense_btn, self.appointment_btn)
        Dialog.setTabOrder(self.appointment_btn, self.dentist_btn)
        Dialog.setTabOrder(self.dentist_btn, self.updt_f_name)
        Dialog.setTabOrder(self.updt_f_name, self.updt_l_name)
        Dialog.setTabOrder(self.updt_l_name, self.updt_pat_id)
        Dialog.setTabOrder(self.updt_pat_id, self.updt_gender)
        Dialog.setTabOrder(self.updt_gender, self.updt_phn)
        Dialog.setTabOrder(self.updt_phn, self.updt_email)
        Dialog.setTabOrder(self.updt_email, self.updt_age)
        Dialog.setTabOrder(self.updt_age, self.updt_reg_dt)
        Dialog.setTabOrder(self.updt_reg_dt, self.updt_addr)
        Dialog.setTabOrder(self.updt_addr, self.updt_occu)
        Dialog.setTabOrder(self.updt_occu, self.updt_refr)
        Dialog.setTabOrder(self.updt_refr, self.updt_file_name)
        Dialog.setTabOrder(self.updt_file_name, self.updt_depart)
        Dialog.setTabOrder(self.updt_depart, self.updt_comp)
        Dialog.setTabOrder(self.updt_comp, self.updt_med_findings)
        Dialog.setTabOrder(self.updt_med_findings, self.return_pat)
        Dialog.setTabOrder(self.return_pat, self.files_hist_btn)
        Dialog.setTabOrder(self.files_hist_btn, self.pay_hist_btn)
        Dialog.setTabOrder(self.pay_hist_btn, self.updt_file_btn)
        Dialog.setTabOrder(self.updt_file_btn, self.new_file_btn)
        Dialog.setTabOrder(self.new_file_btn, self.customize_btn)
        Dialog.setTabOrder(self.customize_btn, self.delete_pat)
        Dialog.setTabOrder(self.delete_pat, self.dash_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.dash_btn.setText(_translate("Dialog", "Dashboard"))
        self.appointment_btn.setText(_translate("Dialog", "Appointments"))
        self.dentist_btn.setText(_translate("Dialog", "Dentists"))
        self.payment_btn.setText(_translate("Dialog", "Payments"))
        self.expense_btn.setText(_translate("Dialog", "Expense"))
        self.label_4.setText(_translate("Dialog", " Medico App "))
        self.patient_btn.setText(_translate("Dialog", "Patients"))
        self.q1.setText(_translate("Dialog", "  1.Blood Diseases?"))
        self.q2.setText(_translate("Dialog", "  2.Smoker?"))
        self.q3.setText(_translate("Dialog", "  3.Bleeding Disorder?"))
        self.q4.setText(_translate("Dialog", "  4.Hepatitis?"))
        self.q5.setText(_translate("Dialog", "  5.Diabetes?"))
        self.q6.setText(_translate("Dialog", "  6.Epilepsy?"))
        self.q7.setText(_translate("Dialog", "  7.Cardiac or Kidney Diseases?"))
        self.q8.setText(_translate("Dialog", "  8.Abnormal Blood Pressure?"))
        self.q9.setText(_translate("Dialog", "  9.Currently on any Medications?"))
        self.q10.setText(_translate("Dialog", "  10.Respitory Diasease/ Asthma?"))
        self.q11.setText(_translate("Dialog", "  11.Bleeding Gums during Brushing Teeth?"))
        self.q12.setText(_translate("Dialog", "  12.Allergies (penicillin, aspirin, local anesthesia, codeine, others)?"))
        self.q13.setText(_translate("Dialog", "  13.Nervous Person?"))
        self.q14.setText(_translate("Dialog", "  14.(Female) Currently Pregnant?"))
        self.q15.setText(_translate("Dialog", "  15.(Female) Currently breastfeeding?"))
        self.q16.setText(_translate("Dialog", "  16.Has any other chronic diasease not stated above?"))
        self.findings_label_2.setText(_translate("Dialog", "  Medical History"))
        self.updt_q1.setText(_translate("Dialog", "  yes"))
        self.updt_q2.setText(_translate("Dialog", "  yes"))
        self.updt_q3.setText(_translate("Dialog", "  yes"))
        self.updt_q4.setText(_translate("Dialog", "  yes"))
        self.updt_q5.setText(_translate("Dialog", "  yes"))
        self.updt_q6.setText(_translate("Dialog", "  yes"))
        self.updt_q7.setText(_translate("Dialog", "  yes"))
        self.updt_q8.setText(_translate("Dialog", "  yes"))
        self.updt_q9.setText(_translate("Dialog", "  yes"))
        self.updt_q10.setText(_translate("Dialog", "  yes"))
        self.updt_q11.setText(_translate("Dialog", "  yes"))
        self.updt_q12.setText(_translate("Dialog", "  yes"))
        self.updt_q13.setText(_translate("Dialog", "  yes"))
        self.updt_q14.setText(_translate("Dialog", "  yes"))
        self.updt_q15.setText(_translate("Dialog", "  yes"))
        self.updt_q16.setText(_translate("Dialog", "  yes"))
        self.f_name_labl.setText(_translate("Dialog", "First Name:"))
        self.updt_f_name.setText(_translate("Dialog", "N/A"))
        self.l_name_labl.setText(_translate("Dialog", "Last Name:"))
        self.updt_l_name.setText(_translate("Dialog", "N/A"))
        self.phn_labl.setText(_translate("Dialog", "Phone:"))
        self.email_labl.setText(_translate("Dialog", "Email:"))
        self.updt_phn.setText(_translate("Dialog", "N/A"))
        self.updt_email.setText(_translate("Dialog", "N/A"))
        self.updt_addr.setText(_translate("Dialog", "N/A"))
        self.addr_labl.setText(_translate("Dialog", "Address:"))
        self.updt_occu.setText(_translate("Dialog", "N/A"))
        self.updt_refr.setText(_translate("Dialog", "N/A"))
        self.occu_labl.setText(_translate("Dialog", "Occupation:"))
        self.refr_labl.setText(_translate("Dialog", "Reference:"))
        self.depart_labl.setText(_translate("Dialog", "(If lives abroad) Date of Departure:"))
        self.updt_depart.setText(_translate("Dialog", "N/A"))
        self.comp_labl.setText(_translate("Dialog", "Complain:"))
        self.pat_id_labl.setText(_translate("Dialog", "Patient ID:"))
        self.updt_pat_id.setText(_translate("Dialog", "N/A"))
        self.age_labl.setText(_translate("Dialog", "Age:"))
        self.updt_age.setText(_translate("Dialog", "N/A"))
        self.gender_labl.setText(_translate("Dialog", "Gender:"))
        self.updt_gender.setText(_translate("Dialog", "N/A"))
        self.reg_dt_labl.setText(_translate("Dialog", "Date of Reg:"))
        self.updt_reg_dt.setText(_translate("Dialog", "N/A"))
        self.findings_label.setText(_translate("Dialog", "Medical Findings"))
        self.return_pat.setText(_translate("Dialog", "Return"))
        self.delete_pat.setText(_translate("Dialog", "Delete"))
        self.updt_med_findings.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI \'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.customize_btn.setText(_translate("Dialog", "Customize"))
        self.new_file_btn.setText(_translate("Dialog", "Add New File"))
        self.updt_comp.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI \'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.file_name_labl.setText(_translate("Dialog", "File Name:"))
        self.updt_file_name.setText(_translate("Dialog", "N/A"))
        self.updt_file_btn.setText(_translate("Dialog", "Update File"))
        self.pay_hist_btn.setText(_translate("Dialog", "Payment History"))
        self.files_hist_btn.setText(_translate("Dialog", "Files History"))
