# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patients_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 680)
        Dialog.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.side_bar = QtWidgets.QWidget(Dialog)
        self.side_bar.setGeometry(QtCore.QRect(0, 0, 160, 681))
        self.side_bar.setStyleSheet("\n"
"background-color: rgba(170, 170, 255,.5);\n"
"")
        self.side_bar.setObjectName("side_bar")
        self.patient_btn = QtWidgets.QPushButton(self.side_bar)
        self.patient_btn.setGeometry(QtCore.QRect(10, 180, 140, 40))
        self.patient_btn.setStyleSheet("\n"
"QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Medico_modern/patientdownload .png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.patient_btn.setIcon(icon)
        self.patient_btn.setObjectName("patient_btn")
        self.dash_btn = QtWidgets.QPushButton(self.side_bar)
        self.dash_btn.setGeometry(QtCore.QRect(10, 80, 140, 40))
        self.dash_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Medico_modern/dashboard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dash_btn.setIcon(icon1)
        self.dash_btn.setObjectName("dash_btn")
        self.appointment_btn = QtWidgets.QPushButton(self.side_bar)
        self.appointment_btn.setGeometry(QtCore.QRect(10, 480, 140, 40))
        self.appointment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Medico_modern/appointmentdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.appointment_btn.setIcon(icon2)
        self.appointment_btn.setObjectName("appointment_btn")
        self.dentist_btn = QtWidgets.QPushButton(self.side_bar)
        self.dentist_btn.setGeometry(QtCore.QRect(10, 580, 140, 40))
        self.dentist_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Medico_modern/dentistimages.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dentist_btn.setIcon(icon3)
        self.dentist_btn.setObjectName("dentist_btn")
        self.payment_btn = QtWidgets.QPushButton(self.side_bar)
        self.payment_btn.setGeometry(QtCore.QRect(10, 280, 140, 40))
        self.payment_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Medico_modern/billingdownload (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.payment_btn.setIcon(icon4)
        self.payment_btn.setObjectName("payment_btn")
        self.expense_btn = QtWidgets.QPushButton(self.side_bar)
        self.expense_btn.setGeometry(QtCore.QRect(10, 380, 140, 40))
        self.expense_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.expense_btn.setIcon(icon4)
        self.expense_btn.setObjectName("expense_btn")
        self.label_4 = QtWidgets.QLabel(self.side_bar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 161, 51))
        self.label_4.setStyleSheet("\n"
"text-decoration: underline;\n"
"font: 22pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(255, 255, 255,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_4.setObjectName("label_4")
        self.patient_table = QtWidgets.QTableWidget(Dialog)
        self.patient_table.setGeometry(QtCore.QRect(260, 180, 911, 431))
        self.patient_table.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.patient_table.setStyleSheet("background-color: rgba(255, 255, 255,.85);\n"
"font:  12pt \"Segoe UI \";")
        self.patient_table.setObjectName("patient_table")
        self.patient_table.setColumnCount(6)
        self.patient_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.patient_table.setHorizontalHeaderItem(5, item)
        self.fname_srch = QtWidgets.QLabel(Dialog)
        self.fname_srch.setGeometry(QtCore.QRect(180, 20, 101, 31))
        self.fname_srch.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.fname_srch.setObjectName("fname_srch")
        self.fname_srch_edit = QtWidgets.QTextEdit(Dialog)
        self.fname_srch_edit.setGeometry(QtCore.QRect(280, 20, 141, 31))
        self.fname_srch_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.fname_srch_edit.setObjectName("fname_srch_edit")
        self.lname_srch = QtWidgets.QLabel(Dialog)
        self.lname_srch.setGeometry(QtCore.QRect(460, 20, 101, 31))
        self.lname_srch.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.lname_srch.setObjectName("lname_srch")
        self.lname_srch_edit = QtWidgets.QTextEdit(Dialog)
        self.lname_srch_edit.setGeometry(QtCore.QRect(560, 20, 141, 31))
        self.lname_srch_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.lname_srch_edit.setObjectName("lname_srch_edit")
        self.phn_srch = QtWidgets.QLabel(Dialog)
        self.phn_srch.setGeometry(QtCore.QRect(180, 60, 101, 31))
        self.phn_srch.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.phn_srch.setObjectName("phn_srch")
        self.phone_srch_edit = QtWidgets.QTextEdit(Dialog)
        self.phone_srch_edit.setGeometry(QtCore.QRect(280, 60, 141, 31))
        self.phone_srch_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.phone_srch_edit.setObjectName("phone_srch_edit")
        self.search_btn = QtWidgets.QPushButton(Dialog)
        self.search_btn.setGeometry(QtCore.QRect(195, 105, 75, 30))
        self.search_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.patid_srch = QtWidgets.QLabel(Dialog)
        self.patid_srch.setGeometry(QtCore.QRect(460, 60, 101, 31))
        self.patid_srch.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.patid_srch.setObjectName("patid_srch")
        self.patid_srch_edit = QtWidgets.QTextEdit(Dialog)
        self.patid_srch_edit.setGeometry(QtCore.QRect(560, 60, 141, 31))
        self.patid_srch_edit.setStyleSheet("QTextEdit:focus{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QTextEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    font: 12pt \"Segoe UI\";\n"
"}\n"
"")
        self.patid_srch_edit.setObjectName("patid_srch_edit")
        self.add_patient_btn = QtWidgets.QPushButton(Dialog)
        self.add_patient_btn.setGeometry(QtCore.QRect(1025, 615, 140, 30))
        self.add_patient_btn.setStyleSheet("QPushButton{\n"
"\n"
"\n"
"font:  14pt \"Segoe UI \";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"background-color: rgb(170, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:focus{\n"
"    background-color: rgb(161, 161, 161);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.add_patient_btn.setIcon(icon)
        self.add_patient_btn.setObjectName("add_patient_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1281, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/sam-moghadam-khamseh-I-kDEBUMAaQ-unsplash.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(200, 110, 75, 30))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1030, 620, 140, 30))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.patient_list = QtWidgets.QLabel(Dialog)
        self.patient_list.setGeometry(QtCore.QRect(260, 150, 911, 31))
        self.patient_list.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"\n"
"font:  14pt \"Segoe UI \";")
        self.patient_list.setObjectName("patient_list")
        self.label.raise_()
        self.side_bar.raise_()
        self.patient_table.raise_()
        self.fname_srch.raise_()
        self.fname_srch_edit.raise_()
        self.lname_srch.raise_()
        self.lname_srch_edit.raise_()
        self.phn_srch.raise_()
        self.phone_srch_edit.raise_()
        self.patid_srch.raise_()
        self.patid_srch_edit.raise_()
        self.label_2.raise_()
        self.search_btn.raise_()
        self.label_3.raise_()
        self.add_patient_btn.raise_()
        self.patient_list.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.fname_srch_edit, self.lname_srch_edit)
        Dialog.setTabOrder(self.lname_srch_edit, self.phone_srch_edit)
        Dialog.setTabOrder(self.phone_srch_edit, self.patid_srch_edit)
        Dialog.setTabOrder(self.patid_srch_edit, self.search_btn)
        Dialog.setTabOrder(self.search_btn, self.add_patient_btn)
        Dialog.setTabOrder(self.add_patient_btn, self.dash_btn)
        Dialog.setTabOrder(self.dash_btn, self.patient_btn)
        Dialog.setTabOrder(self.patient_btn, self.payment_btn)
        Dialog.setTabOrder(self.payment_btn, self.expense_btn)
        Dialog.setTabOrder(self.expense_btn, self.appointment_btn)
        Dialog.setTabOrder(self.appointment_btn, self.dentist_btn)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.patient_btn.setText(_translate("Dialog", "Patients"))
        self.dash_btn.setText(_translate("Dialog", "Dashboard"))
        self.appointment_btn.setText(_translate("Dialog", "Appointments"))
        self.dentist_btn.setText(_translate("Dialog", "Dentists"))
        self.payment_btn.setText(_translate("Dialog", "Payments"))
        self.expense_btn.setText(_translate("Dialog", "Expense"))
        self.label_4.setText(_translate("Dialog", " Medico App "))
        item = self.patient_table.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "PatID"))
        item = self.patient_table.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "First Name"))
        item = self.patient_table.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Last Name"))
        item = self.patient_table.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Sex"))
        item = self.patient_table.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Age"))
        item = self.patient_table.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Phone"))
        self.fname_srch.setText(_translate("Dialog", "First Name"))
        self.lname_srch.setText(_translate("Dialog", "Last Name"))
        self.phn_srch.setText(_translate("Dialog", "Phone"))
        self.search_btn.setText(_translate("Dialog", "Search"))
        self.patid_srch.setText(_translate("Dialog", "Patient ID"))
        self.add_patient_btn.setText(_translate("Dialog", "Add Patients"))
        self.patient_list.setText(_translate("Dialog", "Patients List"))
